### ISSUE TITLE
typo in composer.json file dependency

### ISSUE THREAD

**Issue by dirnbauer** [fnagel/pluploadfe_powermail#1]
hello Felix,

IMHO there is a typo in the require section of  composer.json

`"felixnagel/pluploadfe": "^6.0"`

instead of 

`"felixnagel/puploadfe": "^6.0",`

please have a look at it.
composer installation fails.

thank you,
kurt

**Comment by fnagel** [comment]
Hi Kurt!

Thanks for your bug report. Very appreciated!

You are right. This is a (quite bad) typo. Fixed in master. 1.0.1 release is on the way!

Regards
Felix
